name: CI Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

env:
  PYTHON_VERSION: 3.11

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup-py
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Install Dependencies
        run: pip install -e .[dev]

      - name: Lint
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Install Dependencies
        run: pip install -e .[test]

      - name: Test
        run: make test

      - name: Archive Code Coverage Results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ env.PYTHON_VERSION }}
          path: coverage.xml
